# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Quiz.create( question:"Did you had a pet when you where a child?", level:1)
Quiz.create( question:"Where did you grow up?", level:1)
Quiz.create( question:"If you could take a plane tomorrow to go anywhere, what would be your destination?", level:1)
Quiz.create( question:"How many brothers and sisters do you have?", level:1)
Quiz.create( question:"What is your favorite movie?", level:1)
Quiz.create( question:"What is your favorite book?", level:1)
Quiz.create( question:"Did you recently go somewhere for the first of your life?", level:1)
Quiz.create( question:"What was your favorite music band back in your teenage years ?", level:1)
Quiz.create( question:"How do you like your eggs?", level:1)
Quiz.create( question:"Do you have a collection of some kind?", level:1)
Quiz.create( question:"What was your first job?", level:1)
Quiz.create( question:"What is your favorite song ?", level:1)
Quiz.create( question:"What is your favorite color ?", level:1)
Quiz.create( question:"What is your parents name?", level:1)
Quiz.create( question:"What is your favorite dish?", level:1)
Quiz.create( question:"What is your favorite season?", level:1)
Quiz.create( question:"Tell 2 fact about you and one lie, lets see if the other can find out", level:1)
Quiz.create( question:"If you were a vegetable what would it be ?", level:1)
Quiz.create( question:"What is your job?", level:1)


Quiz.create( question:"What is your favorite family tradition?", level:2)
Quiz.create( question:"What would be a perfect saturday night?", level:2)
Quiz.create( question:"Do you have any phobia?", level:2)
Quiz.create( question:"What make you the most proud in your life?", level:2)
Quiz.create( question:"Do you have a favorite quote?", level:2)
Quiz.create( question:"What is your plan for tonight?", level:2)
Quiz.create( question:"What is your plan for tomorrow?", level:2)
Quiz.create( question:"Which travel you did, left you with the most pleasant memories?", level:2)
Quiz.create( question:"Do you drink alcohol ? If the answer is yes tell your best drinking story", level:2)
Quiz.create( question:"Do you drink alcohol ? If the answer is yes tell the worst thing that happen when you were drunk?", level:2)
Quiz.create( question:"What did you do with your first pay?", level:2)
Quiz.create( question:"Have you been injured by a wild animal in your life? How?", level:2)
Quiz.create( question:"If you could give life to any fictive character who would you choose?", level:2)
Quiz.create( question:'What do you regret from "the good old time?"', level:2)
Quiz.create( question:"Tomorrow you wake up as an animal, which is it and why?", level:2)
Quiz.create( question:"Which character in a movie would you like be in real life?", level:2)
Quiz.create( question:"If you had to create a  tagline for your life what would it be?", level:2)
Quiz.create( question:"What did you do yesterday?", level:2)
Quiz.create( question:"What is the funniest thing that happened to you?", level:2)
Quiz.create( question:"Are you naturally gifted for something useless ?", level:2)
Quiz.create( question:"How long was your longest relation with someone?", level:2)
Quiz.create( question:"What is the biggest injury you ever had?", level:2)
Quiz.create( question:"With which celebrity you would spend your life?", level:2)
Quiz.create( question:"Have you ever got so drunk that you slept in the toilets ? if yes how and why?", level:2)
Quiz.create( question:"What is the most dangerous thing you ever did?", level:2)
Quiz.create( question:"What is your ultimate goal in life ?", level:2)
Quiz.create( question:"tell a joke", level:2)
Quiz.create( question:"You have to choose a spirit animal, which is it and why?", level:2)
Quiz.create( question:"What do you like the most about you?", level:2)


Quiz.create( question:"Have you ever commited any crime ? (even small ones)", level:3)
Quiz.create( question:"Did you tried drugs? Which one ?", level:3)
Quiz.create( question:"When did you do your first time ?And tell what went wrong (Because every first time meet some problems along the ride)", level:3)
Quiz.create( question:"What is the worst thing you did to anyone?", level:3)
Quiz.create( question:"What is your worst sex story ever ?", level:3)
Quiz.create( question:"What is the last incredibly dumb thing you did?", level:3)
Quiz.create( question:"Have you ever been unfaithful?", level:3)
Quiz.create( question:"What is your deepest secret ?", level:3)
Quiz.create( question:"Did you ever got injuries from sex ?", level:3)
Quiz.create( question:"With which celebrity you would spend the night?", level:3)
Quiz.create( question:"What is your worst nightmare ?", level:3)
Quiz.create( question:"What is the most insane thing you ever seen ?", level:3)
Quiz.create( question:"What is the most embarassing  situation you could put your self through for a prize of 1 million dollars?", level:3)
Quiz.create( question:"Do you have a secret dream?", level:3)
Quiz.create( question:"What is the most incredible thing you ever did? (You are allowed to brag but not too much)", level:3)
Quiz.create( question:"What is the meaning of life ? (exept for the answer : 42)", level:3)
Quiz.create( question:"Who was the most insane person you ever know and why?", level:3)
Quiz.create( question:"Which movie make you cry every single time and which part of this movie?", level:3)
Quiz.create( question:"If you add to choose one : sex or food ?", level:3)

